name: GitHub Actions Demo

run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
  
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [15.x]
    
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.6.0
        with:
          # Version Spec of the version to use. Examples: 12.x, 10.15.1, >=10.15.0.
          node-version: '12.x'
          # Target architecture for Node to use. Examples: x86, x64. Will use system architecture by default.
          architecture: default
          # Used to specify a package manager for caching in the default directory. Supported values: npm, yarn, pnpm.
          cache: npm
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run: npm run build --if-present
      - name: Test
        run: npm test
      
  lint:
  
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.14.0]
    
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.6.0
        with:
          # Version Spec of the version to use. Examples: 12.x, 10.15.1, >=10.15.0.
          node-version: ${{ matrix.node-version }}
          # Target architecture for Node to use. Examples: x86, x64. Will use system architecture by default.
          architecture: default
          # Used to specify a package manager for caching in the default directory. Supported values: npm, yarn, pnpm.
          cache: npm
      - name: Run lint
        run: npm lint
